use_frameworks!

target 'CardinalKit_Example' do
  pod 'CardinalKit', :path => '../'
  
  # CK Sample Pods
   
  pod 'Granola', :git => 'https://github.com/CardinalKit/Granola.git', :branch => 'main'
  
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'
  pod 'GoogleSignIn'
  pod 'Charts'

end
